import SiteNav from "../../components/SiteNav";
import SiteFooter from "../../components/SiteFooter";

export const metadata = { title: "Terms of Service · Reputix" };

export default function Terms() {
  return (
    <main className="min-h-screen">
      <SiteNav />
      <article className="pt-32 pb-20 px-4 sm:px-6">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-4xl sm:text-5xl font-extrabold text-gray-900">
            Terms of Service
          </h1>
          <p className="mt-3 text-sm text-gray-500">Last updated: April 2026</p>

          <div className="prose prose-gray mt-10 space-y-8 text-gray-700 leading-relaxed">
            <Section n={1} title="Acceptance of Terms">
              By accessing or using Reputix (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you are using Reputix on behalf of a business, you represent that you have the authority to bind that business to these terms. You must be at least 18 years old to create an account and use the Service.
            </Section>

            <Section n={2} title="Description of Service">
              Reputix is an AI-powered reputation management platform that monitors online reviews, articles, and social media mentions for local businesses. The Service includes automated review response generation, crisis alerts, competitor benchmarking, and periodic reports. Reputix does not guarantee specific business outcomes, rating improvements, or review volumes.
            </Section>

            <Section n={3} title="Account Registration">
              You must provide accurate, current, and complete information during registration. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. One account is permitted per business location unless you subscribe to a multi-location plan.
            </Section>

            <Section n={4} title="Free Trial">
              New accounts may access a free trial: 30 days for Starter, 14 days for Growth and Pro. No credit card is required to start a trial. All features of the selected plan are available during the trial period. We reserve the right to modify or discontinue the free trial at any time.
            </Section>

            <Section n={5} title="Billing and Payment">
              Paid subscriptions are billed via Stripe in AED (or the local currency you selected). By subscribing, you authorize Reputix to charge your payment method on a recurring basis until you cancel. If a payment fails, we will retry up to 2 times before suspending access. Subscriptions are non-refundable for partial billing periods, but you retain access until the end of your current billing cycle after cancellation.
            </Section>

            <Section n={6} title="AI-Generated Content">
              All responses and insights generated by the Reputix AI are suggestions, not guaranteed solutions. Positive review responses may be automatically posted if you enable autopilot mode. Negative review responses always require your explicit approval before publication. Reputix is not liable for any consequences arising from content you choose to publish. You remain solely responsible for all content posted under your business account.
            </Section>

            <Section n={7} title="Data and Privacy">
              We collect business information, review data, and usage analytics to deliver the Service. We do not sell your data to third parties. The Service relies on third-party providers including Google APIs, OpenAI, Supabase, and Stripe. See our Privacy Policy for full details on data handling.
            </Section>

            <Section n={8} title="Intellectual Property">
              Reputix owns all rights to the platform, software, branding, and underlying AI systems. Reports and insights generated for your business are licensed to you for internal business use. You may not resell, redistribute, or use Reputix outputs to train competing AI systems.
            </Section>

            <Section n={9} title="Prohibited Use">
              You agree not to: (a) generate or solicit fake reviews; (b) use Reputix to manipulate or attack competitors; (c) abuse the Service through automated scraping beyond your own business data; (d) use the Service for any illegal activity or in violation of UAE law; (e) attempt to reverse-engineer or bypass access controls.
            </Section>

            <Section n={10} title="Service Availability">
              We target 99.9% uptime but do not guarantee uninterrupted service. Planned maintenance will be announced in advance when possible. Reputix is not liable for downtime caused by third-party APIs (Google, OpenAI, etc.) or force majeure events.
            </Section>

            <Section n={11} title="Limitation of Liability">
              To the maximum extent permitted by law, Reputix&apos;s total liability to you for any claim arising from or related to the Service is limited to the amount you paid to Reputix in the 12 months preceding the claim. Reputix is not liable for indirect, incidental, consequential, or punitive damages.
            </Section>

            <Section n={12} title="Termination">
              Either party may terminate this agreement at any time. Upon termination, your data is retained for 90 days and then permanently deleted. You may request a data export at any time before deletion.
            </Section>

            <Section n={13} title="Changes to Terms">
              We may update these Terms from time to time. Material changes will be communicated via email at least 30 days before taking effect. Continued use of the Service after the effective date constitutes acceptance of the updated Terms.
            </Section>

            <Section n={14} title="Governing Law">
              These Terms are governed by the laws of the Dubai International Financial Centre (DIFC), United Arab Emirates. Any disputes shall be resolved exclusively in the DIFC Courts.
            </Section>

            <Section n={15} title="Contact">
              For questions about these Terms, contact us at{" "}
              <a href="mailto:legal@reputix.io" className="text-brand-700 font-semibold">
                legal@reputix.io
              </a>
              .
            </Section>
          </div>
        </div>
      </article>
      <SiteFooter />
    </main>
  );
}

function Section({ n, title, children }: { n: number; title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-xl font-bold text-gray-900">
        {n}. {title}
      </h2>
      <p className="mt-3">{children}</p>
    </section>
  );
}
